In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('Data/test/analysis-stock-change-5-quoted.csv', quotechar='|')

In [8]:
df.head()

,text,stock_change,compound,neg,neu,pos
0,AAK AB: AAK förväntar sig ett rörelseresultat ...,5.87,0.0000,0.0,1.000,0.000
1,AAK AB: AAK:s delårsrapport för det andra kvar...,-7.47,0.5574,0.0,0.796,0.204
2,AAK AB: AAK:s delårsrapport för det första kva...,-5.01,0.0000,0.0,1.000,0.000
3,Nya prekliniska data kring tasquinimod kommer ...,10.65,0.0000,0.0,1.000,0.000
4,Active Biotech Delårsrapport januari - septemb...,10.65,0.0000,0.0,1.000,0.000

In [9]:
df.dtypes

text             object
stock_change    float64
compound        float64
neg             float64
neu             float64
pos             float64
dtype: object

In [10]:
df.columns

Index(['text', 'stock_change', 'compound', 'neg', 'neu', 'pos'], dtype='object')

In [11]:
df[df['stock_change'] >= 5]
df

,text,stock_change,compound,neg,neu,pos
0,AAK AB: AAK förväntar sig ett rörelseresultat ...,5.87,0.0000,0.000,1.000,0.000
1,AAK AB: AAK:s delårsrapport för det andra kvar...,-7.47,0.5574,0.000,0.796,0.204
2,AAK AB: AAK:s delårsrapport för det första kva...,-5.01,0.0000,0.000,1.000,0.000
3,Nya prekliniska data kring tasquinimod kommer ...,10.65,0.0000,0.000,1.000,0.000
4,Active Biotech Delårsrapport januari - septemb...,10.65,0.0000,0.000,1.000,0.000
...,...,...,...,...,...,...
15896,Storskogen Group AB: Första dag för handel i S...,31.17,-0.3182,0.161,0.839,0.000
15897,Ändring av antal aktier och röster i Truecalle...,-5.16,0.2960,0.000,0.804,0.196
15898,Truecaller AB: Truecaller samarbetar med India...,23.16,0.6597,0.000,0.707,0.293
15899,Truecaller AB: Tredje kvartalet 2021: Truecall...,33.84,0.7906,0.000,0.652,0.348
15900,Nordisk Bergteknik AB: Meddelande om stabilise...,19.69,0.0000,0.000,1.000,0.000